### ISSUE TITLE
Add SwipeToRefresh and Unlimited scrolling(Pull from Top, Pull from Bottom)

### ISSUE THREAD

**Issue by roideuniverse** [carrot/recycler-core#18]

**Comment by BrandonRomano** [comment]
I would base this off of the classes you create in #16, but extend them so users have the option if they want it or not

**Comment by roideuniverse** [comment]
Yes, Thanks. Good point. However I was thinking first try to make it a part of the View, if that doesn't work out then maybe try with the classes in #16

**Comment by BrandonRomano** [comment]
As long as it would be easily toggleable between different screens (one screen might have PTR, one screen might not).

We've found ourselves using the same layout, (Like `BaseRecyclerActivity`), and I would be worried if we set it to the view it would be a little more challenging to enable/disable recycling from an activity level?

I'm sure there's a way so that's actually not a concern, just wanted to bring it up so you could think about it!

**Comment by roideuniverse** [comment]
:+1:

**Comment by roideuniverse** [comment]
Going to close this as we now have SwipeRefresh, and Unlimited Scrolling when scrolling down.

Ref #41
